/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package liv.tudor;

import java.io.File;
import java.nio.charset.Charset;
import java.nio.charset.IllegalCharsetNameException;
import org.apache.commons.cli.HelpFormatter;

public class App {

  public String getGreeting() {
    return "Hello world.";
  }

  private static void showHelp() {
    HelpFormatter formatter = new HelpFormatter();
    formatter.printHelp("import program", CmdLineParams.OPTIONS);
  }

  public static void main(String[] args) {
    CmdLineParams params = null;
    try {
      params = new CmdLineParams(args);
    } catch (Exception e) {
      System.out.println("Wrong parameters:" + e.getMessage());
      showHelp();
    }

    File f = new File(params.getFileName());
    if (!f.exists()) {
      System.out.println("File " + params.getFileName() + " not found");
      showHelp();
      System.exit((1));
    }
        try {
            Charset.forName(params.getEncoding());
        } catch (IllegalCharsetNameException e) {
            System.out.println("Invalid encoding : " + params.getEncoding());
            showHelp();
            System.exit(1);
        }

    try {
      //connect to database
    } catch (Exception e) {
      System.out.println("Cannot connect to database");
      showHelp();
      System.exit(1);
    }

    // finally do work
  }
}
